import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./pages/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#292931",
        "surface-container-lowest": "#0d0e14",
        "surface-bright": "#383940",
        "on-surface": "#e3e1eb",
        "on-secondary-container": "#ffb86c",
        "secondary-container": "#794700",
        "on-tertiary-fixed": "#001f25",
        "error-container": "#93000a",
        "on-primary-container": "#4e2484",
        "secondary-fixed": "#ffdcbc",
        "surface-variant": "#33343c",
        "primary-fixed-dim": "#d7baff",
        "surface-container-highest": "#33343c",
        "on-tertiary": "#00363e",
        primary: "#d7baff",
        "on-surface-variant": "#ccc3d3",
        "on-secondary": "#492900",
        "tertiary-fixed": "#a3eeff",
        "on-secondary-fixed": "#2c1600",
        "on-tertiary-container": "#00434d",
        "on-primary": "#411478",
        "surface-dim": "#12131a",
        "on-primary-fixed-variant": "#593090",
        "tertiary-fixed-dim": "#75d4e8",
        "primary-container": "#bd93f9",
        "surface-container-low": "#1a1b22",
        "inverse-primary": "#714aaa",
        "surface-tint": "#d7baff",
        "on-tertiary-fixed-variant": "#004e5a",
        secondary: "#ffb86c",
        "primary-fixed": "#eddcff",
        "surface-container": "#1e1f26",
        surface: "#12131a",
        outline: "#968e9c",
        "on-error": "#690005",
        "inverse-surface": "#e3e1eb",
        "tertiary-container": "#53b4c7",
        "on-background": "#e3e1eb",
        "inverse-on-surface": "#2f3037",
        "secondary-fixed-dim": "#ffb86c",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "outline-variant": "#4a4451",
        "on-primary-fixed": "#290055",
        background: "#12131a",
        tertiary: "#75d4e8",
        "on-secondary-fixed-variant": "#683c00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "label-sm": ["Space Mono"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Playfair Display"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["72px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
